- package-lock.json
- package.json
- src/app/create/context.ts
- src/app/create/page.tsx
- src/hooks/useMount.ts
* use-funnel 라이브러리를 설치
* 단계별 타입 선언
* create 페이지에 funnel.Render 구조 생성
> SCRUM-121 feat: useFunnel 설정

- .github/workflow/build-check.yml
Pull request merge 전 eslint, build check 추가
> chore: eslint build check setup

- src/app/create/_components/taskForm/TaskForm.tsx
- src/app/create/context.ts
- src/app/create/page.tsx
- src/components/clearableInput/ClearableInput.tsx
할 일 등록 단계 중, 첫 단계(TaskInput)인 할 일 입력을 작업했습니다.
* ClearableInput 공통컴포넌트를 구현
* use-funnel context type 네이밍 수정
> SCRUM-80 feat: 할 일 입력 필드 기능 구현

- src/app/create/_components/taskInput/TaskInput.tsx
- src/app/create/page.tsx
[SCRUM-81](https://ssak3.atlassian.net/jira/software/projects/SCRUM/list?selectedIssue=SCRUM-81)
* 16자 이내라면 버튼 활성화
* 16자 이상이라면 버튼 비활성화 및 유효성 검사 문구 추가
* 파일명 변경 누락된 점이 있어서 이를 반영했습니다.
TaskForm.tsx -> TaskInput.tsx
[SCRUM-81]: https://ssak3.atlassian.net/browse/SCRUM-81?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCRUM-81 feat: 유효성 검사 문구 추가

- src/app/create/_components/taskInput/TaskInput.tsx
- src/app/create/page.tsx
[SCRUM-122](https://ssak3.atlassian.net/jira/software/projects/SCRUM/list?selectedIssue=SCRUM-122)
use-funnel을 history property를 사용하여 다음 스텝으로 이동합니다.
deadlineDate과 deadlineTime은 임시로 적용하였습니다.
[SCRUM-122]: https://ssak3.atlassian.net/browse/SCRUM-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCRUM-122 feat: use-funnel 다음 스텝으로 이동 구현

- src/app/globals.css
- src/app/page.tsx
- tailwind.config.ts
없음
- typography, color 디자인 토큰 추가
- 이상한 점이나, 개선이 필요한 부분이 있다면 말씀해주세요!
> chore: typography, color 추가

- package-lock.json
- src/app/action/start/page.tsx
- src/app/globals.css
- src/components/ui/button.tsx
[SCRUM-123]
버튼 컴포넌트를 공통화 작업했습니다.
버튼 사용 예시를 첨부드립니다.
[SCRUM-123]: https://ssak3.atlassian.net/browse/SCRUM-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCRUM-123 버튼컴포넌트 공통화

- src/app/create/_components/taskInput/TaskInput.tsx
- src/app/create/_components/timeSelectedComponent/TimeSelectedComponent.tsx
- src/components/timePicker/Picker.tsx
- src/components/timePicker/TimePicker.tsx
- src/types/time.ts
[SCRUM-119]
[SCRUM-119]: https://ssak3.atlassian.net/browse/SCRUM-119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCRUM-119 feat: 마감시간 선택 UI 구현

- src/app/create/_components/DateSelectedComponent/DateSelectedComponent.tsx
- src/app/create/_components/bufferTime/BufferTime.tsx
- src/app/create/_components/estimatedTimeInput/EstimatedTimeInput.tsx
- src/app/create/_components/smallActionInput/SmallActionInput.tsx
- src/app/create/_components/taskInput/TaskInput.tsx
- src/app/create/_components/timeSelectedComponent/TimeSelectedComponent.tsx
- src/app/create/context.ts
- src/app/create/page.tsx
- src/types/create.ts
[SCRUM-43]
[SCRUM-43]: https://ssak3.atlassian.net/browse/SCRUM-43?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCRUM-43 사용자는 할 일을 시작하기 전에 버퍼타임이 적용된 것을 확인할 수 있기를 원한다

- .vscode/settings.json
- package-lock.json
- package.json
- src/app/(create)/_components/estimatedTimeInput/EstimatedTimeInput.tsx
- src/app/(create)/_components/instantTaskTypeInput/InstantTaskTypeInput.tsx
- src/app/(create)/_components/taskTypeInput/TaskTypeInput.tsx
- src/components/timePicker/TimePicker.tsx
- src/components/timePicker/Wheel.tsx
- src/components/timePicker/style.css
- src/utils/transformTaskData.tsx
[SCRUM-136]
- 직접 구현한 timepicker에 더 이상 리소스를 투자하기 힘들어 라이브러리로 대체한 작업입니다.
https://github.com/user-attachments/assets/df9133d5-090e-4e0f-a339-ed2bf5a888b5
[SCRUM-136]: https://ssak3.atlassian.net/browse/SCRUM-136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCRUM-136 time picker 라이브러리 대체

- src/app/(create)/_components/bufferTime/BufferTime.tsx
- src/app/(create)/_components/estimatedTimeInput/EstimatedTimeInput.tsx
- src/app/(create)/_components/taskInput/TaskInput.tsx
- src/app/(create)/_components/taskTypeInput/TaskTypeInput.tsx
- src/app/(create)/_components/timeSelectedComponent/TimeSelectedComponent.tsx
- src/app/(create)/scheduled-create/page.tsx
- src/components/timePicker/TimePicker.tsx
- src/utils/formatBufferTime.ts
- src/utils/getBufferTime.ts
[SCRUM-137]
할 일 등록 과정에서 발생하는 버그들을 1차 수정했습니다.
버그 목록은 Jira를 참고해주세요.
[SCRUM-137]: https://ssak3.atlassian.net/browse/SCRUM-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCRUM-137 fix: 할 일 등록 일부 버그 수정

- src/app/home-page/_components/InProgressTaskItem.tsx
[SCRUM-25]
시간 표시 애니메이션 수정했습니다.
[SCRUM-25]: https://ssak3.atlassian.net/browse/SCRUM-25?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: 시간 표시 애니메이션 수정

- src/app/api/tasks/current-week/route.ts
- src/app/home-page/_components/AllTaskItem.tsx
- src/app/home-page/_components/InProgressTaskItem.tsx
- src/app/home-page/page.tsx
- src/services/taskService.ts
- src/types/task.ts
[SCRUM-25]
시간 표시 컴포넌트 수정했습니다.
[SCRUM-25]: https://ssak3.atlassian.net/browse/SCRUM-25?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Scrum 25 사용자로서 할 일 목록을 확인할 수 있는 서비스가 필요합니다

- src/app/(create)/_components/characterDialog/CharacterDialog.tsx
- src/app/(create)/_components/instantTaskTypeInput/InstantTaskTypeInput.tsx
- src/app/(create)/_components/taskTypeInput/TaskTypeInput.tsx
- src/app/(create)/instant-create/page.tsx
- src/app/(create)/scheduled-create/page.tsx
- src/app/home-page/page.tsx
- src/middleware.ts
[SCRUM-147]
- 작업 생성 후 홈페이지로 이동 및 모달 띄우기
- middleware에서 토큰없을 때, rewrite 제한
- 작업 생성 첫 단계 - 뒤로가기 경로 추가
- 홈페이지 Suspense 적용
[SCRUM-147]: https://ssak3.atlassian.net/browse/SCRUM-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCRUM-147 feat: 작업 생성 후 홈 페이지로 이동 및 모달 띄우기

- src/app/immersion/[taskId]/ImmersionPageClient.tsx
> fix: 시간 표시 로직 수정

- src/app/api/tasks/home/route.ts
- src/lib/serverKy.ts
- 서버 사이드에서 활용할 fetch interceptor를 추가했습니다.
- 우선 홈 화면에서는 테스트에 성공했습니다.
- 다른 api도 테스트 해보셔도 좋습니다.
> feat: 서버사이드용 ky 추가

- src/app/home-page/page.tsx
> fix: 툴팁 수정 및 화면 전체 mt 제거

- src/app/home-page/page.tsx
> fix: margin 수정

- src/app/home-page/page.tsx
> fix: margin isAllEmpty일 때만 표시되도록 수정

- next.config.ts
- src/app/(create)/_components/bufferTime/BufferTime.tsx
- src/app/(create)/_components/taskTypeInput/TaskTypeInput.tsx
- src/app/my-page/page.tsx
- src/components/ProfileImage.tsx
- next.config.ts에 hostname이 잘못 설정되어 있던 것을 수정
- 불필요한 상태 제거
- 버퍼타임 계산 로직 미적용된 곳에 추가 적용
- 일부 스타일링 개선
> fix: 마이페이지 프로필 이미지 로딩 에러 수정

- src/app/api/oauth/callback/apple/route.ts
- src/app/api/oauth/callback/kakao/route.ts
- src/lib/serverKy.ts
> chore: login-page redirection added

- src/app/(create)/_components/bufferTime/BufferTime.tsx
- src/app/(create)/_components/estimatedTimeInput/EstimatedTimeInput.tsx
- src/app/(create)/_components/instantTaskTypeInput/InstantTaskTypeInput.tsx
- src/app/(create)/_components/smallActionInput/SmallActionInput.tsx
- src/app/(create)/_components/taskInput/TaskInput.tsx
- src/app/(create)/_components/taskTypeInput/TaskTypeInput.tsx
- src/app/(create)/instant-create/page.tsx
- src/app/(create)/scheduled-create/page.tsx
- src/app/login/page.tsx
- src/components/loader/Loader.tsx
- src/middleware.ts
- 작업 생성 시, loading UI 추가
- 하단 버튼 위치 공통화
> fix: 하단 버튼 위치 수정 / 작업 생성 시, 로딩 ux 개선

- src/app/api/auth/members/me/route.ts
- src/app/login/page.tsx
- src/app/my-page/page.tsx
- src/middleware.ts
- 유저 정보가 없는 경우, 다시 불러올 수 있도록 로직 수정
> fix: 유저 정보가 없는 경우 불러올 수 있도록 수정

- src/app/onboarding/page.tsx
- src/app/personal-info/page.tsx
- src/app/terms/page.tsx
> fix: onboarding3 수정

- src/app/(protected)/onboarding/page.tsx
> fix: 이미지 svg -> png

- src/app/(protected)/onboarding/page.tsx
> fix: 이미지 교체

- src/app/(auth)/login/page.tsx
- src/app/(protected)/(create)/_components/characterDialog/CharacterDialog.tsx
- src/app/(protected)/(root)/page.tsx
- src/app/api/oauth/callback/apple/route.ts
- src/app/api/oauth/callback/kakao/route.ts
- src/app/layout.tsx
- 로그인 시, deviceId, deviceType 관련 데이터 제거
- 스크롤이 되지 않는 이슈 수정
- 작업 생성 후 모달이 뜨지 않는 이슈 수정
> remove: 로그인 device 관련 데이터 제거

- src/app/(protected)/(create)/_components/taskTypeChip/TaskTypeChip.tsx
- src/app/(protected)/(root)/_components/CreateTaskSheet.tsx
- Image 컴포넌트에 loading: eager 추가 (priority x)
- img 태그 사용
> test: svg 이미지 렌더링 속도 향상 테스트

- src/app/(protected)/(create)/_components/taskTypeChip/TaskTypeChip.tsx
- next/Image에 priority를 넣은 후 렌더링 테스트
> test: 이미지 priority 속성 적용

- src/app/(protected)/(create)/_components/dateSelectedComponent/DateSelectedComponent.tsx
- src/app/(protected)/(create)/_components/taskInput/TaskInput.tsx
- src/app/(protected)/(create)/_components/timeSelectedComponent/TimeSelectedComponent.tsx
- src/components/clearableInput/ClearableInput.tsx
- src/components/datePicker/DatePicker.tsx
- src/components/timePicker/Wheel.tsx
- src/components/timePicker/style.css
- src/components/toast/Toast.tsx
- src/components/ui/calendar.tsx
- src/hooks/useInitialTime.ts
- tailwind.config.ts
- 마감 시간 타임 피커의 스크롤 기능 개선
- 바텀시트 기능 개선
- 토스트 메세지 애니메이션 추가
- 일부 스타일링 개선
> refactor: 할 일 등록 qa 2차 수정

- src/app/oauth/callback/kakao/page.tsx
> test: 인앱 브라우저 리다이렉션 테스트

- src/app/oauth/callback/kakao/page.tsx
Reverts depromeet/16th-team3-FE#103
> Revert "test: 인앱 브라우저 리다이렉션 테스트"

- src/app/(auth)/login/page.tsx
- src/app/(protected)/(create)/_components/bufferTime/BufferTime.tsx
- src/app/(protected)/(create)/_components/estimatedTimeInput/EstimatedTimeInput.tsx
- src/app/(protected)/(create)/_components/instantTaskTypeInput/InstantTaskTypeInput.tsx
- src/app/(protected)/(create)/_components/smallActionInput/SmallActionInput.tsx
- src/app/(protected)/(create)/_components/taskTypeInput/TaskTypeInput.tsx
> style: 레이아웃 조정(심사용)

- src/app/(auth)/login/page.tsx
- src/app/(protected)/(create)/_components/bufferTime/BufferTime.tsx
- src/app/(protected)/(create)/_components/characterDialog/CharacterDialog.tsx
- src/app/(protected)/(create)/_components/dateSelectedComponent/DateSelectedComponent.tsx
- src/app/(protected)/(create)/_components/estimatedTimeInput/EstimatedTimeInput.tsx
- src/app/(protected)/(create)/_components/instantTaskTypeInput/InstantTaskTypeInput.tsx
- src/app/(protected)/(create)/_components/smallActionInput/SmallActionInput.tsx
- src/app/(protected)/(create)/_components/taskInput/TaskInput.tsx
- src/app/(protected)/(create)/instant-create/page.tsx
- src/app/(protected)/(create)/scheduled-create/page.tsx
- src/app/(protected)/(root)/page.tsx
- src/app/(protected)/signup-complete/page.tsx
- src/app/api/tasks/scheduled/route.ts
- src/app/api/tasks/urgent/route.ts
- 작은 행동 입력 스타일링 수정
- 여유있게 시작(버퍼타임 화면에서 뒤로가기 기능 개선 / 이슈 수정
> refactor: 작은 행동 입력 스타일링 및 일부 기능 개선

- src/app/(protected)/(create)/_components/characterDialog/CharacterDialog.tsx
- src/app/(protected)/(create)/_components/estimatedTimeInput/EstimatedTimeInput.tsx
- src/app/(protected)/(root)/_components/TaskDetailSheet.tsx
- src/app/(protected)/(root)/page.tsx
- src/app/(protected)/edit/buffer-time/[taskId]/page.tsx
- src/app/(protected)/edit/deadline-date/[taskId]/page.tsx
- src/app/(protected)/edit/estimated-time/[taskId]/page.tsx
- src/app/(protected)/edit/layout.tsx
- src/app/(protected)/edit/small-action/[taskId]/page.tsx
- 홈화면에서 할 일 수정에 대한 qa 피드백 반영
- 스타일링 수정
- 예상 소요시간 기능 개선
> refactor: 할 일 수정 스타일링 및 일부 기능 개선

- package-lock.json
- package.json
- Next.js middleware 취약점을 해결한 버전으로 업그레이드
> next.js version upgrade(15.2.4)

- src/app/(protected)/(root)/_components/InProgressTaskItem.tsx
- src/app/(protected)/edit/deadline-date/[taskId]/page.tsx
- 홈화면 바텀시트에 Drawer 적용
- 할 일 수정 시, 즉시 시작 바텀시트 하드코딩된 값 수정
> fix: 할 일 수정 시, 즉시 시작 바텀시트 하드코딩 값 수정 / 바텀시트 Drawer 적용

- src/app/(protected)/immersion/[taskId]/ImmersionPageClient.tsx
- src/app/(protected)/immersion/_components/DetailGoals/DetailGoals.tsx
> fix: 세부목표 키보드 test

- src/app/(protected)/(root)/_components/InProgressTaskItem.tsx
- src/app/(protected)/(root)/page.tsx
- 세션스토리지를 확인하는 위치를 자식 컴포넌트로 변경
- map 인자에 index를 추가하여 첫 번째 태스크만 띄우도록 개선
> refactor: 홈 바텀시트 팝업 로직 개선

- src/app/(protected)/immersion/_components/DetailGoals/DetailGoals.tsx
> test: 체크버튼, 완료버튼 터치 테스트

- src/app/(protected)/(create)/_components/bufferTime/BufferTime.tsx
- src/app/(protected)/(create)/_components/dateSelectedComponent/DateSelectedComponent.tsx
- src/app/(protected)/(create)/_components/estimatedDayPicker/EstimatedDayPicker.tsx
- src/app/(protected)/(create)/_components/estimatedTimeInput/EstimatedTimeInput.tsx
- src/app/(protected)/(create)/_components/estimatedTimePicker/EstimatedTimePicker.tsx
- src/app/(protected)/(create)/_components/headerTitle/HeaderTitle.tsx
- src/app/(protected)/(create)/_components/smallActionChip/SmallActionChip.tsx
- src/app/(protected)/(create)/_components/timeSelectedComponent/TimeSelectedComponent.tsx
- src/app/(protected)/(create)/scheduled-create/page.tsx
- src/app/(protected)/(root)/_components/TaskDetailSheet.tsx
- src/app/(protected)/(root)/page.tsx
- src/app/(protected)/(root)/weekly-tasks/page.tsx
- src/app/api/tasks/scheduled/route.ts
- src/components/timePicker/Wheel.tsx
- src/components/timePicker/style.css
- src/components/ui/drawer.tsx
- src/utils/dateFormat.ts
- src/utils/getBufferTime.ts
[SCRUM-167]
- 2차 UT 결과를 바탕으로 예상 소요시간 기능 재구성
- 시간 / 분 / 일 케이스 별로 예외처리
- 입력란 -> 타임 피커로 전환
[SCRUM-167]: https://ssak3.atlassian.net/browse/SCRUM-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCRUM-167 refactor: 예상소요 시간 타임피커 적용

- src/app/(protected)/(create)/_components/estimatedTimeInput/EstimatedTimeInput.tsx
[SCRUM-169]
- 마감 시간 계산 로직 방식 수정
[SCRUM-169]: https://ssak3.atlassian.net/browse/SCRUM-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCRUM-169 fix: 마감시간 계산법 수정

- src/app/(protected)/(create)/_components/estimatedTimeInput/EstimatedTimeInput.tsx
- src/app/(protected)/(create)/scheduled-create/page.tsx
[SCRUM-170]
- 할 일 등록 시, 예상 소요시간 화면에서 뒤로가기 이슈 수정
[SCRUM-170]: https://ssak3.atlassian.net/browse/SCRUM-170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCRUM-170 fix: 뒤로가기 버그 수정

- src/app/(protected)/(create)/_components/estimatedTimePicker/EstimatedTimePicker.tsx
- src/app/(protected)/(create)/_components/failedDialog/FailedDialog.tsx
- src/app/(protected)/(create)/_components/taskTypeInput/TaskTypeInput.tsx
- src/app/(protected)/(create)/scheduled-create/page.tsx
- src/app/(protected)/(root)/page.tsx
- src/app/api/tasks/scheduled/route.ts
- src/components/timePicker/Wheel.tsx
- src/utils/transformTaskData.tsx
[SCRUM-173]
- triggerActionAlarmTime 계산 로직 개선
- 생성 실패 예외처리 추가
[SCRUM-173]: https://ssak3.atlassian.net/browse/SCRUM-173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCRUM-173 refactor: triggerActionAlarmTime 계산법 개선 / 예외처리 추가

- src/app/(protected)/(root)/weekly-tasks/page.tsx
- src/app/(protected)/immersion/[taskId]/ImmersionPageClient.tsx
- src/app/(protected)/immersion/_components/DetailGoals/DetailGoals.tsx
> fix: 몰입화면 QA 진행중

- src/app/(protected)/immersion/_components/DetailGoals/DetailGoals.tsx
> fix: 세부목표 키보드 올라오는 테스트중

- src/app/(protected)/(create)/_components/dateSelectedComponent/DateSelectedComponent.tsx
- src/app/(protected)/(create)/_components/taskInput/TaskInput.tsx
- src/app/(protected)/(create)/_components/timeSelectedComponent/TimeSelectedComponent.tsx
- src/app/api/auth/withdraw/route.ts
- src/components/timePicker/Wheel.tsx
- src/utils/getBufferTime.ts
- 버퍼타임 5분 단위
- 타임피커 snap mode로 변경
- 마감일 수정 시, 바텀시트 띄우지 않기
- 자정버튼 클릭 시, 바텀시트 닫지 않기
> fix: 할일 등록 qa - 2차

- src/app/(protected)/(create)/_components/bufferTime/BufferTime.tsx
- src/components/timePicker/TimePicker.tsx
- src/components/timePicker/Wheel.tsx
- src/components/timePicker/style.css
- src/utils/getBufferTime.ts
> fix: 할일 등록 QA - 3

- src/app/(auth)/login/page.tsx
- throughTalk 파라미터를 안드로이드에서는 false로 변경하도록 추가
> chore: 카카오 로그인 안드로이드 이슈 예외처리

- src/app/(protected)/my-page/_component/Persona.tsx
- src/app/(protected)/my-page/_component/PersonaSection.tsx
- src/app/(protected)/my-page/characters/page.tsx
- src/app/(protected)/my-page/page.tsx
- src/app/layout.tsx
- src/components/component/Badge.tsx
> fix: 빌드 에러 수정

- src/app/(protected)/my-page/_component/Persona.tsx
- src/app/(protected)/my-page/_component/PersonaSection.tsx
- src/app/(protected)/my-page/characters/page.tsx
- src/app/(protected)/my-page/page.tsx
- src/app/(protected)/my-page/setting/page.tsx
- src/app/layout.tsx
- 마이페이지 페르소나 이름 스타일링 수정
- 일부 예외처리 수정
> fix: 마이페이지 일부 스타일링 수정

- .github/workflows/github-actions.yml
- src/app/(auth)/login/page.tsx
- src/app/(protected)/(root)/page.tsx
- src/app/api/tasks/[taskId]/retrospectives/route.ts
- src/app/oauth/callback/apple/page.tsx
- src/app/oauth/callback/kakao/page.tsx
- src/lib/serverTask.ts
- src/middleware.ts
- Enhanced Apple login stability and fixed several bugs.
> fix: apple login error

- src/app/(protected)/(create)/_components/characterDialog/CharacterDialog.tsx
- src/app/(protected)/(create)/_components/dateSelectedComponent/DateSelectedComponent.tsx
- src/app/(protected)/(create)/_components/timeSelectedComponent/TimeSelectedComponent.tsx
- src/app/(protected)/(create)/instant-create/page.tsx
- src/app/(protected)/(create)/scheduled-create/page.tsx
- src/app/(protected)/(root)/_components/TaskDetailSheet.tsx
- src/app/(protected)/(root)/page.tsx
- src/app/(protected)/edit/context.ts
- src/app/(protected)/edit/deadline-date/[taskId]/page.tsx
- src/app/api/tasks/scheduled/route.ts
- src/app/api/tasks/urgent/route.ts
- src/app/layout.tsx
- src/components/pinchZoomPreventer/PinchZoomPreventer.tsx
- 할 일 이름 수정이 안 되는 버그 수정
- 작업 생성 시, 캐릭터가 항상 같은 이슈 수정
> refactor: 작업 생성 / 수정 2차 mvp QA

- src/app/(protected)/(root)/_components/CreateTaskSheet.tsx
- src/app/(protected)/(root)/page.tsx
> chore: 홈화면 일부 스타일링 수정

- .vscode/settings.json
- next.config.ts
- minimumCacheTTL을 적용하여 동일한 이미지 요청에 대해 캐싱된 이미지를 불러올 수 있도록 개선
- 캐시를 무효화할 상황이 없음으로 값을 1년으로 설정
> refactor: minimumCacheTTL 적용

- src/lib/serverKy.ts
Reverts depromeet/16th-team3-FE#155
> Revert "remove: error exceptions in Ky"

- src/app/(protected)/(create)/_components/characterDialog/CharacterDialog.tsx
- src/app/(protected)/(create)/instant-create/page.tsx
- src/app/(protected)/(create)/scheduled-create/page.tsx
- src/app/(protected)/(root)/_components/todayTaskTabWrapper/TodayTaskTabWrapper.tsx
- src/app/(protected)/(root)/page.tsx
- src/app/(protected)/my-page/characters/page.tsx
- src/app/(protected)/my-page/page.tsx
- src/app/(protected)/retrospection/[taskId]/_components/RetrospectCommentContent.tsx
- src/app/layout.tsx
- 일부 dynamic import 제거
- textarea 확대 버그 수정
> refactor: dynamic import enhance

- src/app/(protected)/action/complete/_component/CharacterMotivation.tsx
- src/app/(protected)/retrospection/[taskId]/_components/RetrospectFocusContent.tsx
> refactor: 회고 QA

- src/app/(protected)/(root)/_components/todayTaskTabWrapper/TodayTaskTabWrapper.tsx
- src/app/(protected)/(root)/page.tsx
- src/app/(protected)/(root)/weekly-tasks/page.tsx
- src/app/(protected)/action/complete/page.tsx
- src/app/(protected)/action/remind/[taskId]/ActionRemindPageClient.tsx
- src/app/(protected)/my-page/task-detail/[taskId]/ExpiredTaskDetailPage.tsx
- src/app/(protected)/onboarding/page.tsx
- src/hooks/useWebViewMessage.ts
- src/lib/serverKy.ts
- 전역변수를 추가하여 토큰 재발급 동시성 문제 해결
- 불필요한 코드 제거
close #163
> fix: 토큰 재발급 동시성 이슈 수정

- src/lib/serverKy.ts
- serverKy에 토큰 관리 로직 수정
close #166
> fix: 마이페이지 - 백그라운드에서 다시 접속 시 발생하는 에러

- .vscode/settings.json
- src/app/(protected)/(root)/page.tsx
- src/app/(protected)/(root)/weekly-tasks/page.tsx
- src/app/(protected)/immersion/[taskId]/ImmersionPageClient.tsx
- src/app/(protected)/my-page/page.tsx
- src/app/(protected)/my-page/setting/page.tsx
- src/app/(protected)/signup-complete/page.tsx
- src/app/globals.css
- src/app/oauth/callback/apple/page.tsx
- src/app/oauth/callback/kakao/page.tsx
- src/components/loader/Loader.tsx
- src/components/spurtyLoader/SpurtyLoader.tsx
- tailwind.config.ts
- 로딩 화면에서 스피너를 스퍼티로 교체
- 로그인 정보 설정 페이지로 이동
close #164
> refactor: loading 화면 개선

- package-lock.json
- package.json
- src/components/spurtyLoader/SpurtyLoader.tsx
- src/lib/serverKy.ts
- 토큰 재발급 함수에 batchRequestsOf 메서드 적용
close #169
> fix: 동시성 이슈 수정

- src/app/(protected)/my-page/characters/page.tsx
- src/app/(protected)/my-page/page.tsx
- src/app/(protected)/my-page/task-detail/[taskId]/ExpiredTaskDetailPage.tsx
- src/app/(protected)/retrospection/[taskId]/RetrospectionPageClient.tsx
- 회고 페이지 스타일 버그 수정
- 회고 생성 시, 잘못된 데이터 전송 이슈 수정
- 마이페이지 캐싱 무효화 적용 이슈 수정
close #171
> fix: 회고 페이지 일부 버그 수정

- package-lock.json
- package.json
- src/app/(protected)/(create)/_components/characterDialog/CharacterDialog.tsx
- src/app/(protected)/(create)/instant-create/page.tsx
- src/app/(protected)/(root)/_components/header/headerBar/HeaderBar.tsx
- src/app/(protected)/(root)/_components/todayTaskTabWrapper/TodayTaskTabWrapper.tsx
- src/app/(protected)/(root)/page.tsx
- src/app/(protected)/my-page/page.tsx
- tailwind.config.ts
- 몰입 화면 접근 전, prefetch를 적용하여 빠른 접근
- 페르소나 모달 띄울 때, 애니메이션 적용
- Sharp 라이브러리 추가
> refactor: 몰입 화면 prefetch 적용

- src/lib/serverKy.ts
- src/middleware.ts
- middleware에 토큰 재발급 로직 추가
close #176
> fix: refreshToken이 없음에도 홈화면으로 일부 접근이 가능한 이슈

- src/app/(protected)/my-page/setting/page.tsx
- src/middleware.ts
- 로그인 페이지로 리다이렉트하는 조건 수정 및 runtime 옵션 제거
- 마이페이지 공통 컴포넌트 적용
> chore: middleware 리다이렉트 조건 수정

- src/components/ProfileImage.tsx
- 프로필 이미지 memo 적용
- 카카오 기본 이미지의 경우, 스퍼티 프로필 적용
close #182
> chore: 카카오 프로필 이미지 개선
